### PR TITLE
Create tv_grab_url

### PR DESCRIPTION
**Pull request by Chris230291**
Added URL xmltv grabber

### CODE REVIEW

**Comment by tobbenb** [comment]
Please add info about it in the changelog of the readme

**Comment by Chris230291** [comment]
I think I have done what you wanted.

**Comment by tobbenb** [comment]
You added it to the wrong file. The readme is generated from the readme-vars file. Should have read the pull request template 😉

**Comment by Chris230291** [comment]
ok

**Review by tobbenb — APPROVED** [review]

**Pull request merged**
