### PR TITLE
Fix for picons Release 4.2

### PR DESCRIPTION
**Pull request by thelamer**
So the app has some pretty cool behaviour, on spinup it will add variables to an existing config file if they are missing and needed, likely needed for upgrades and additions. So we can put the bare minimum picons pathing into a config file and have it there on first boot for this container. 

Also added the extraction of the PNGs from the tarball.

### CODE REVIEW

**Comment by CHBMB** [comment]
@thelamer I don't think personally there's any real downside to setting `"prefer_picon":` to `true`

Unless @tobbenb can think of one?

**Comment by tobbenb** [comment]
The PR is OK by me. Apart from failing to build 😜

**Comment by CHBMB** [comment]
@tobbenb Isn't that a bug in the pipeline that if you make changes to a PR after it's failed to build, then even if it would build normally after that it still fails?  I might be wrong, seem to recall @aptalca telling me about it I think.

**Comment by thelamer** [comment]
@CHBMB @tobbenb no it is failing randomly on pulling xmltv from sourceforge on the arm builds . The bug you are referring to was with the old build setup. 
You can see the error in the build log.

**Comment by tobbenb** [comment]
Xmltv moved to github now, so we can change the source

**Pull request merged**
