### PR TITLE
Permission fix for /dev/dri/*

### PR DESCRIPTION
**Pull request by ErAzOr2k**
change ID of video be able to access /dev/dri/* files within tvheadend

### CODE REVIEW

**Comment by tobbenb** [comment]
Sorry, but haven't gotten around to test this yet. I'll do it in the weekend.

**Comment by tobbenb** [comment]
I have tested it now, and it doesn't work as you haven't taking into account that the GID might already be used.
Isn't it better to just add the abc user to the same GID as on host and not use the video group?

**Comment by thelamer** [comment]
This needs logic to detect possible collisions in the GID, and to allow the user to define the GID via an environment variable optionally. IE:

```
#!/usr/bin/with-contenv bash

# Add UID to video group
if [ -z ${VIDEO_GID+x} ]; then
        usermod -a -G video abc
else
        # Check if the GID is taken and swap to 65533
        CURRENT=$(getent group ${VIDEO_GID} | awk -F: '{print $1}')
        if [ -z "${CURRENT}" ] || [ "${CURRENT}" == 'video' ]; then
                groupmod -g ${VIDEO_GID} video
                usermod -a -G video abc
        else
                groupmod -g 65533 ${CURRENT}
                groupmod -g ${VIDEO_GID} video
                usermod -a -G video abc
        fi
fi
```

**Comment by tobbenb** [comment]
Closing this due to lack of respons and we moved to a new build system. Will implement the same workaround as plex use.

**Pull request closed without merging**
