### PR TITLE
add perl-lwp-useragent-determined which is needed for tv_grab_zz_sdjson_sqlite

### PR DESCRIPTION
**Pull request by danofun**
[linuxserverurl]: https://linuxserver.io
[linuxserver.io][linuxserverurl]

### CODE REVIEW

**Comment by danofun** [comment]
I'll work on a more complete solution by updating all of XMLTV.

**Comment by tobbenb** [comment]
The only thing needed to use the latest version of xmltv is to change the variable for the version at the top of the dockerfile.

**Comment by danofun** [comment]
Correct. However, [additional modules](https://github.com/XMLTV/xmltv) appear to be missing. Alpine has packages for:
`perl-date-calc
perl-http-message
perl-lwp-protocol-https
perl-uri`
These addition modules do not have an alpine package:
`DateTime::Format::ISO8601
DateTime::Format::SQLite
File::HomeDir
SOAP::Lite
XML::DOM
HTTP::Cache::Transparent
Tk
Tk::TableMatrix
JSON::XS
Log::TraceMessages
PerlIO::gzip`
They can be installed in this, or similar, fashion:
`export PERL_MM_USE_DEFAULT=1
export PERL_EXTUTILS_AUTOINSTALL="--defaultdeps"
perl -MCPAN -e'install($_) for qw( module1 module2 module3 )'`

**Comment by tobbenb** [comment]
The additional modules are in patches/cpanfile, so they are installed.

**Pull request closed without merging**
