### PR TITLE
Add support for hardware accelerated transcoding on AMD platforms

### PR DESCRIPTION
**Pull request by nRaecheR**
[linuxserverurl]: https://linuxserver.io
[linuxserver.io][linuxserverurl]

### CODE REVIEW

**Comment by j0nnymoe** [comment]
Can you confirm this is working? I don't believe we have any AMD Hardware within the team to test this with.

**Comment by nRaecheR** [comment]
Yes, it works the same way as with Intel hardware. You need to map device /dev/dri/renderD128 to container and then add hwaccel options for VA-API to ffmpeg. 
The additional package just adds the needed VA-API driver for AMD hardware (radeonsi_drv_video.so)

I've tested it with an AMD Athlon 200GE with Radeon Vega Graphics and ffmpeg from the command line.

**Comment by tobbenb** [comment]
So you haven't built this local and tested that it actually works in TVheadend?

**Comment by nRaecheR** [comment]
Sure, i build the image locally with my patch, verified that the driver for the AMD video decoder is present and transcoded a recorded file from within the new created container.

**Comment by tobbenb** [comment]
But not through tvheadend?

**Comment by nRaecheR** [comment]
Not yet, I will test it as soon as I find out how to create a streaming profile with hardware accelerated transcoding enabled in TVHeadEnd.
The interface for that is the command line from ffmpeg. It should be exactly the same for AMD and Intel graphics, so if it works with Intel before my patch it will work with AMD after adding the Radeon video driver.

**Comment by nRaecheR** [comment]
I can now confirm that it works at least with the following codecs:

- libx264_vaapi
- hevc_vaapi
- vp9_vaapi

It even works with hardware decoding enabled but I have to disable the checkbox "Deinterlace" for that.  And scaling of the video won't work, the log states an error message like this in that case:

```
2019-05-28 17:42:58.081 [  ERROR] libav: AVFilter: Failed to render parameter buffer: 6 (invalid VASurfaceID).
```

I have no comparison to Intel hardware so I can't tell if these limitations are present with this hardware too. The processor load is very low with hardware acceleration enabled, I checked it against software encoding. 

I can't see the ffmpeg process in the process list, it seems TVHeadEnd uses libav as shared object. Is there any way to force the usage of the external ffmpeg executable?

Here's the snippet from a successful transcoding run: 

```
2019-05-28 17:41:26.465 [   INFO] transcode: 0009: 01:HEVC: ==> Using profile libx264_vaapi
2019-05-28 17:41:26.465 [   INFO] transcode: 0009: 02:EAC3: ==> Copy
2019-05-28 17:41:26.465 [   INFO] transcode: 0009: 03:EAC3: ==> Copy
2019-05-28 17:41:26.465 [   INFO] transcode: 0009: 05:DVBSUB: ==> Filtered out
2019-05-28 17:41:27.401 [WARNING] libav: AVCodecContext: B frames are not supported (0x1) by the underlying driver.
2019-05-28 17:41:27.401 [WARNING] libav: AVCodecContext: Warning: some packed headers are not supported (want 0xd, got 0).
```

**Comment by nRaecheR** [comment]
Coul you please enlighten me why you won't merge my pull request? Is there something missing?

**Comment by thelamer** [comment]
I think it boils down to team members not having hardware to test and confirm functionality . We do install libva Intel though so the entire concept is sound. Please be patient and allow @tobbenb to confirm this stuff.

**Comment by tobbenb** [comment]
@nRaecheR Sorry for the lack of response, but I haven't had time lately to track PRs as normal life was busy.

I'm a little bit concerned about the deinterlacing issues though. Also scaling is a concern. I have hardware to test on for Intel, but not sure if I still have any source for tvheadend.

I'm currently away on holiday, so I have no time to check it until mid next week.

**Comment by nRaecheR** [comment]
Thanks for the info, if you need further help please let me know!

**Comment by aptalca** [comment]
We're testing hw acceleration with amd for jellyfin. We'll test it for this as well. Thanks again for the PR.

**Pull request merged**
