### PR TITLE
Added URL XMLTV grabber

### PR DESCRIPTION
**Pull request by Chris230291**

### CODE REVIEW

**Comment by Roxedus** [comment]
What is the purpose of this newline change?

**Comment by Roxedus** [comment]
all this change does, is removing a newline, as you can see in the "Files changed" tab on top

**Comment by Chris230291** [comment]
Why has it done that?

**Comment by Roxedus** [comment]
That i dont know. maybe you forgot to add all the files in your git commit

**Comment by Chris230291** [comment]
Did the file already exist?
I made a pull request a while ago for the same thing, but it never worked because of permissions I think?
I changed the files permissions to 777, build the container myself and it started working. So I'd like to apply those changes if possible?

**Comment by Chris230291** [comment]
So maybe the newline change was done automatically when I uploaded the file?
The only change I made was to the permissions of the file so that it actually works.

**Comment by Gronda74** [comment]
Is this something that would fix issue #188 (https://github.com/linuxserver/docker-tvheadend/issues/188)?

**Pull request closed without merging**
